language: rust
# use trusty for newer openblas
sudo: required
dist: trusty
matrix:
  include:
    - rust: 1.13.0
      env:
       - FEATURES='test'
    - rust: stable
      env:
       - FEATURES='test'
    - rust: beta
      env:
       - FEATURES='test'
    - rust: nightly
      env:
       - FEATURES='test'
       - BENCH=1
branches:
  only:
    - master
addons:
  apt:
    packages:
      - libopenblas-dev
script:
  - |
      cargo build --verbose --no-default-features &&
      cargo test --verbose --no-default-features &&
      cargo test --release --verbose --no-default-features &&
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      CARGO_TARGET_DIR=target/ cargo test --manifest-path=serialization-tests/Cargo.toml --verbose &&
      CARGO_TARGET_DIR=target/ cargo test --manifest-path=numeric-tests/Cargo.toml --verbose &&
      CARGO_TARGET_DIR=target/ cargo test --manifest-path=parallel/Cargo.toml --verbose &&
      ([ "$BENCH" != 1 ] || cargo bench --no-run --verbose --features "$FEATURES")
