language: rust
# use trusty for newer openblas
sudo: required
dist: trusty
matrix:
  include:
    - rust: 1.31.0
      env:
       - FEATURES='test docs'
    - rust: stable
      env:
       - FEATURES='test docs'
    - rust: beta
      env:
       - FEATURES='test docs'
    - rust: nightly
      env:
       - FEATURES='test docs'
       - IS_NIGHTLY=1
env:
  global:
    - HOST=x86_64-unknown-linux-gnu
    - CARGO_INCREMENTAL=0
branches:
  only:
    - master
    - 0.10.x
addons:
  apt:
    packages:
      - libopenblas-dev
      - gfortran
before_script:
  - rustup component add rustfmt clippy
script:
  - |
      cargo fmt --all -- --check &&
      cargo clippy &&
      ./scripts/all-tests.sh "$FEATURES" "$IS_NIGHTLY"
