language: rust
# use trusty for newer openblas
sudo: required
dist: trusty
matrix:
  include:
    - rust: beta
      env:
       - FEATURES='test'
    - rust: nightly
      env:
       - FEATURES='test'
       - BENCH=1
branches:
  only:
    - master
addons:
  apt:
    packages:
      - libopenblas-dev
script:
  - |
      cargo build --verbose &&
      cargo test --verbose &&
      ([ -z "$FEATURES" ] || cargo build --verbose --features "$FEATURES") &&
      ([ -z "$FEATURES" ] || cargo test --verbose --features "$FEATURES") &&
      ([ "$BENCH" != 1 ] || cargo bench --no-run --verbose --features "$FEATURES")
