language: rust
# use trusty for newer openblas
sudo: required
dist: trusty
matrix:
  include:
    - rust: 1.40.0
      env:
       - FEATURES='test docs'
       - RUSTFLAGS='-D warnings'
    - rust: stable
      env:
       - FEATURES='test docs'
       - RUSTFLAGS='-D warnings'
    - rust: beta
      env:
       - FEATURES='test docs'
       - CHANNEL='beta'
       - RUSTFLAGS='-D warnings'
    - rust: nightly
      env:
       - FEATURES='test docs'
       - CHANNEL='nightly'
env:
  global:
    - HOST=x86_64-unknown-linux-gnu
    - CARGO_INCREMENTAL=0
addons:
  apt:
    packages:
      - libopenblas-dev
      - gfortran
script:
  - ./scripts/all-tests.sh "$FEATURES" "$CHANNEL"
